use std::{fs, path::Path, process::Command};

use anyhow::{Context, Result, bail};
use serde_json::Value;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ActionStatus {
    Created,
    Skipped,
    Configured,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScaffoldAction {
    pub path: String,
    pub status: ActionStatus,
    pub detail: Option<String>,
}

const CONFIG_TEMPLATE: &str = r#"{
  "watchlists": [
    {
      "type": "lines",
      "path": "${DOXGUARD_WATCHLIST_DIR}/names.txt",
      "label": "private names"
    }
  ],
  "structural": {
    "windowsPath": true,
    "posixHome": true,
    "privateIp": true,
    "email": true,
    "custom": []
  },
  "allow": {
    "names": [],
    "emails": [],
    "emailDomains": ["example.com", "users.noreply.github.com"],
    "disallowBareAllow": false
  },
  "noise": {
    "minNeedleLength": 2,
    "skipShortKanaGivenNames": true,
    "asciiCaseInsensitive": false
  },
  "exemptPaths": [],
  "failOnSkip": false
}
"#;

fn portable_hook_script(native_hook_abs: &str) -> String {
    // Prefer absolute native path so PATH hijack cannot supply a fake `doxguard`.
    // Fall back to git-dir relative cache, then refuse rather than trusting bare PATH.
    format!(
        r#"#!/usr/bin/env sh
# Generated by doxguard. The watchlist remains outside this repository.
git_dir=$(git rev-parse --git-dir) || exit 2
native_abs="{native}"
if [ -x "$native_abs" ]; then
  exec "$native_abs"
fi
if [ -x "$git_dir/doxguard/hooks/pre-commit" ]; then
  exec "$git_dir/doxguard/hooks/pre-commit"
fi
echo "doxguard: native pre-commit binary missing; run: doxguard install-hooks" >&2
exit 2
"#,
        native = native_hook_abs.replace('\\', "/")
    )
}

const CI_TEMPLATE: &str = r#"name: doxguard

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Scan tracked files (structural patterns only, strict)
        run: npx --yes doxguard@0.1.0 scan --all-tracked --block --strict
"#;

fn create_without_overwrite(cwd: &Path, path: &str, content: &str) -> Result<ScaffoldAction> {
    let target = cwd.join(path);
    if target.exists() {
        return Ok(ScaffoldAction {
            path: path.to_owned(),
            status: ActionStatus::Skipped,
            detail: Some("already exists".to_owned()),
        });
    }
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&target, content)?;
    Ok(ScaffoldAction {
        path: path.to_owned(),
        status: ActionStatus::Created,
        detail: None,
    })
}

fn has_husky(cwd: &Path) -> bool {
    if cwd.join(".husky").exists() {
        return true;
    }
    let Ok(text) = fs::read_to_string(cwd.join("package.json")) else {
        return false;
    };
    let Ok(package): Result<Value, _> = serde_json::from_str(&text) else {
        return false;
    };
    ["dependencies", "devDependencies"]
        .iter()
        .filter_map(|key| package.get(key))
        .any(|dependencies| dependencies.get("husky").is_some())
}

pub fn install_hooks(cwd: &Path) -> Result<Vec<ScaffoldAction>> {
    if has_husky(cwd) {
        return Ok(vec![ScaffoldAction {
            path: ".husky/pre-commit".to_owned(),
            status: ActionStatus::Skipped,
            detail: Some(
                "husky detected; add `doxguard scan --staged --block --strict` to the existing hook"
                    .to_owned(),
            ),
        }]);
    }
    let git_dir_output = Command::new("git")
        .args(["rev-parse", "--git-dir"])
        .current_dir(cwd)
        .output()
        .context("failed to locate git directory")?;
    if !git_dir_output.status.success() {
        bail!("could not locate git directory");
    }
    let git_dir = Path::new(
        std::str::from_utf8(&git_dir_output.stdout)
            .context("git directory was not UTF-8")?
            .trim(),
    );
    let git_dir = if git_dir.is_absolute() {
        git_dir.to_path_buf()
    } else {
        cwd.join(git_dir)
    };
    let hook_dir = git_dir.join("doxguard").join("hooks");
    fs::create_dir_all(&hook_dir)?;
    let cached_hook = hook_dir.join("pre-commit");
    fs::copy(std::env::current_exe()?, &cached_hook)
        .context("failed to cache the native doxguard binary")?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&cached_hook, fs::Permissions::from_mode(0o755))?;
    }
    let native_abs = cached_hook
        .canonicalize()
        .unwrap_or_else(|_| cached_hook.clone());
    let native_abs = native_abs.to_string_lossy();
    let hook_script = portable_hook_script(&native_abs);
    let hook = create_without_overwrite(cwd, ".githooks/pre-commit", &hook_script)?;
    #[cfg(unix)]
    if hook.status == ActionStatus::Created {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(cwd.join(&hook.path), fs::Permissions::from_mode(0o755))?;
    }

    let existing_hooks = Command::new("git")
        .args(["config", "--get", "core.hooksPath"])
        .current_dir(cwd)
        .output()
        .context("failed to read core.hooksPath")?;
    let existing = if existing_hooks.status.success() {
        String::from_utf8_lossy(&existing_hooks.stdout)
            .trim()
            .to_owned()
    } else {
        String::new()
    };
    let mut actions = vec![
        hook,
        ScaffoldAction {
            path: "git-dir/doxguard/hooks/pre-commit".to_owned(),
            status: ActionStatus::Configured,
            detail: Some("direct native hook".to_owned()),
        },
    ];
    if !existing.is_empty() {
        let existing_path = {
            let path = Path::new(&existing);
            if path.is_absolute() {
                path.to_path_buf()
            } else {
                cwd.join(path)
            }
        };
        if existing_path != hook_dir {
            actions.push(ScaffoldAction {
                path: "git config core.hooksPath".to_owned(),
                status: ActionStatus::Skipped,
                detail: Some(format!(
                    "already set to {existing}; left unchanged (call {native_abs} or `doxguard scan --staged --block --strict` from that hooksPath)"
                )),
            });
            return Ok(actions);
        }
    }

    let output = Command::new("git")
        .arg("config")
        .arg("core.hooksPath")
        .arg(&hook_dir)
        .current_dir(cwd)
        .output()
        .context("failed to start git")?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!(
            "could not configure git hooks; is this a git repository? {}",
            stderr.trim()
        );
    }

    actions.push(ScaffoldAction {
        path: "git config core.hooksPath".to_owned(),
        status: ActionStatus::Configured,
        detail: Some("native pre-commit fast path".to_owned()),
    });
    Ok(actions)
}

pub fn initialize(cwd: &Path) -> Result<Vec<ScaffoldAction>> {
    let mut actions = vec![
        create_without_overwrite(cwd, "doxguard.config.json", CONFIG_TEMPLATE)?,
        create_without_overwrite(cwd, ".github/workflows/doxguard.yml", CI_TEMPLATE)?,
    ];
    actions.extend(install_hooks(cwd)?);
    Ok(actions)
}
