use std::{
    fs::{self, OpenOptions},
    io::{ErrorKind, Write},
    path::{Component, Path},
    process::Command,
};

use anyhow::{Context, Result, bail};
use serde_json::Value;

use crate::scan::git_program;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ActionStatus {
    Created,
    Skipped,
    Configured,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScaffoldAction {
    pub path: String,
    pub status: ActionStatus,
    pub detail: Option<String>,
}

const CONFIG_TEMPLATE: &str = r#"{
  "watchlists": [
    {
      "type": "lines",
      "path": "${DOXGUARD_WATCHLIST_DIR}/names.txt",
      "label": "private names"
    }
  ],
  "structural": {
    "windowsPath": true,
    "posixHome": true,
    "privateIp": true,
    "email": true,
    "custom": []
  },
  "allow": {
    "names": [],
    "emails": [],
    "emailDomains": ["example.com", "users.noreply.github.com"],
    "disallowBareAllow": false
  },
  "noise": {
    "minNeedleLength": 2,
    "skipShortKanaGivenNames": true,
    "asciiCaseInsensitive": false
  },
  "exemptPaths": [],
  "failOnSkip": false
}
"#;

fn portable_hook_script() -> &'static str {
    r#"#!/usr/bin/env sh
# Generated by doxguard. The watchlist remains outside this repository.
git_dir=$(git rev-parse --git-dir) || exit 2
if [ -x "$git_dir/doxguard/hooks/pre-commit" ]; then
  exec "$git_dir/doxguard/hooks/pre-commit"
fi
echo "doxguard: native pre-commit binary missing; run: doxguard install-hooks" >&2
exit 2
"#
}

const CI_TEMPLATE: &str = r#"name: doxguard

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "20"
      - name: Scan tracked files (structural patterns only, strict)
        run: npx --yes doxguard@__DOXGUARD_VERSION__ scan --all-tracked --block --strict
"#;

fn ci_template() -> String {
    CI_TEMPLATE.replace("__DOXGUARD_VERSION__", env!("CARGO_PKG_VERSION"))
}

fn skipped_existing(path: &str) -> ScaffoldAction {
    ScaffoldAction {
        path: path.to_owned(),
        status: ActionStatus::Skipped,
        detail: Some("already exists".to_owned()),
    }
}

fn is_link_like(metadata: &fs::Metadata) -> bool {
    if metadata.file_type().is_symlink() {
        return true;
    }
    #[cfg(windows)]
    {
        use std::os::windows::fs::MetadataExt;
        const FILE_ATTRIBUTE_REPARSE_POINT: u32 = 0x400;
        metadata.file_attributes() & FILE_ATTRIBUTE_REPARSE_POINT != 0
    }
    #[cfg(not(windows))]
    {
        false
    }
}

fn write_created_content(
    mut writer: impl Write,
    target: &Path,
    display_path: &str,
    content: &str,
) -> Result<()> {
    if let Err(write_error) = writer.write_all(content.as_bytes()) {
        drop(writer);
        if let Err(cleanup_error) = fs::remove_file(target) {
            bail!(
                "failed to write scaffold file {display_path}: {write_error}; additionally failed to remove the incomplete file: {cleanup_error}"
            );
        }
        return Err(write_error)
            .with_context(|| format!("failed to write scaffold file {display_path}"));
    }
    Ok(())
}

fn create_without_overwrite(cwd: &Path, path: &str, content: &str) -> Result<ScaffoldAction> {
    let relative = Path::new(path);
    if relative.as_os_str().is_empty()
        || relative
            .components()
            .any(|component| !matches!(component, Component::Normal(_)))
    {
        bail!("scaffold path must be a non-empty relative path without traversal: {path}");
    }

    let root = cwd
        .canonicalize()
        .with_context(|| format!("failed to resolve repository root {}", cwd.display()))?;
    let target = root.join(relative);
    match fs::symlink_metadata(&target) {
        Ok(_) => return Ok(skipped_existing(path)),
        Err(error) if error.kind() == ErrorKind::NotFound => {}
        Err(error) => return Err(error).with_context(|| format!("failed to inspect {path}")),
    }

    let mut parent = root.clone();
    if let Some(relative_parent) = relative.parent() {
        for component in relative_parent.components() {
            let Component::Normal(name) = component else {
                unreachable!("relative path components were validated above")
            };
            parent.push(name);
            match fs::symlink_metadata(&parent) {
                Ok(metadata) => {
                    if is_link_like(&metadata) || !metadata.is_dir() {
                        bail!(
                            "refusing to scaffold through a link or non-directory: {}",
                            parent.display()
                        );
                    }
                }
                Err(error) if error.kind() == ErrorKind::NotFound => {
                    match fs::create_dir(&parent) {
                        Ok(()) => {}
                        Err(error) if error.kind() == ErrorKind::AlreadyExists => {}
                        Err(error) => {
                            return Err(error).with_context(|| {
                                format!("failed to create scaffold directory {}", parent.display())
                            });
                        }
                    }
                    let metadata = fs::symlink_metadata(&parent).with_context(|| {
                        format!("failed to verify scaffold directory {}", parent.display())
                    })?;
                    if is_link_like(&metadata) || !metadata.is_dir() {
                        bail!(
                            "refusing to scaffold through a link or non-directory: {}",
                            parent.display()
                        );
                    }
                }
                Err(error) => {
                    return Err(error).with_context(|| {
                        format!("failed to inspect scaffold directory {}", parent.display())
                    });
                }
            }
        }
    }
    let canonical_parent = parent
        .canonicalize()
        .with_context(|| format!("failed to resolve scaffold directory {}", parent.display()))?;
    if !canonical_parent.starts_with(&root) {
        bail!("refusing to create scaffold file outside repository root: {path}");
    }
    let target = canonical_parent.join(
        relative
            .file_name()
            .expect("validated scaffold path has a final component"),
    );
    let file = match OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&target)
    {
        Ok(file) => file,
        Err(error) if error.kind() == ErrorKind::AlreadyExists => {
            return Ok(skipped_existing(path));
        }
        Err(error) => {
            return Err(error).with_context(|| format!("failed to create scaffold file {path}"));
        }
    };
    write_created_content(file, &target, path, content)?;
    Ok(ScaffoldAction {
        path: path.to_owned(),
        status: ActionStatus::Created,
        detail: None,
    })
}

fn has_husky(cwd: &Path) -> bool {
    if cwd.join(".husky").exists() {
        return true;
    }
    let Ok(text) = fs::read_to_string(cwd.join("package.json")) else {
        return false;
    };
    let Ok(package): Result<Value, _> = serde_json::from_str(&text) else {
        return false;
    };
    ["dependencies", "devDependencies"]
        .iter()
        .filter_map(|key| package.get(key))
        .any(|dependencies| dependencies.get("husky").is_some())
}

pub fn install_hooks(cwd: &Path) -> Result<Vec<ScaffoldAction>> {
    if has_husky(cwd) {
        return Ok(vec![ScaffoldAction {
            path: ".husky/pre-commit".to_owned(),
            status: ActionStatus::Skipped,
            detail: Some(
                "husky detected; add `doxguard scan --staged --block --strict` to the existing hook"
                    .to_owned(),
            ),
        }]);
    }
    let git = git_program()?;
    let git_dir_output = Command::new(git)
        .args(["rev-parse", "--git-dir"])
        .current_dir(cwd)
        .output()
        .context("failed to locate git directory")?;
    if !git_dir_output.status.success() {
        bail!("could not locate git directory");
    }
    let git_dir = Path::new(
        std::str::from_utf8(&git_dir_output.stdout)
            .context("git directory was not UTF-8")?
            .trim(),
    );
    let git_dir = if git_dir.is_absolute() {
        git_dir.to_path_buf()
    } else {
        cwd.join(git_dir)
    };
    let hook_dir = git_dir.join("doxguard").join("hooks");
    fs::create_dir_all(&hook_dir)?;
    let cached_hook = hook_dir.join("pre-commit");
    let current_exe = std::env::current_exe()?;
    let same_file = if cached_hook.exists() {
        match (current_exe.canonicalize(), cached_hook.canonicalize()) {
            (Ok(source), Ok(destination)) => source == destination,
            _ => false,
        }
    } else {
        false
    };
    if !same_file {
        fs::copy(&current_exe, &cached_hook)
            .context("failed to cache the native doxguard binary")?;
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&cached_hook, fs::Permissions::from_mode(0o755))?;
    }
    let hook = create_without_overwrite(cwd, ".githooks/pre-commit", portable_hook_script())?;
    #[cfg(unix)]
    if hook.status == ActionStatus::Created {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(cwd.join(&hook.path), fs::Permissions::from_mode(0o755))?;
    }

    let existing_hooks = Command::new(git)
        .args(["config", "--get", "core.hooksPath"])
        .current_dir(cwd)
        .output()
        .context("failed to read core.hooksPath")?;
    let existing = if existing_hooks.status.success() {
        String::from_utf8_lossy(&existing_hooks.stdout)
            .trim()
            .to_owned()
    } else {
        String::new()
    };
    let mut actions = vec![
        hook,
        ScaffoldAction {
            path: "git-dir/doxguard/hooks/pre-commit".to_owned(),
            status: ActionStatus::Configured,
            detail: Some("direct native hook".to_owned()),
        },
    ];
    if !existing.is_empty() {
        let existing_path = {
            let path = Path::new(&existing);
            if path.is_absolute() {
                path.to_path_buf()
            } else {
                cwd.join(path)
            }
        };
        if existing_path != hook_dir {
            actions.push(ScaffoldAction {
                path: "git config core.hooksPath".to_owned(),
                status: ActionStatus::Skipped,
                detail: Some(format!(
                    "already set to {existing}; left unchanged (call the git-dir cached hook or `doxguard scan --staged --block --strict` from that hooksPath)"
                )),
            });
            return Ok(actions);
        }
    }

    let output = Command::new(git)
        .arg("config")
        .arg("core.hooksPath")
        .arg(&hook_dir)
        .current_dir(cwd)
        .output()
        .context("failed to start git")?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!(
            "could not configure git hooks; is this a git repository? {}",
            stderr.trim()
        );
    }

    actions.push(ScaffoldAction {
        path: "git config core.hooksPath".to_owned(),
        status: ActionStatus::Configured,
        detail: Some("native pre-commit fast path".to_owned()),
    });
    Ok(actions)
}

pub fn initialize(cwd: &Path) -> Result<Vec<ScaffoldAction>> {
    let ci_template = ci_template();
    let mut actions = vec![
        create_without_overwrite(cwd, "doxguard.config.json", CONFIG_TEMPLATE)?,
        create_without_overwrite(cwd, ".github/workflows/doxguard.yml", &ci_template)?,
    ];
    actions.extend(install_hooks(cwd)?);
    Ok(actions)
}

#[cfg(test)]
mod tests {
    use std::io;

    use tempfile::tempdir;

    use super::*;

    struct FailingWriter;

    impl Write for FailingWriter {
        fn write(&mut self, _buffer: &[u8]) -> io::Result<usize> {
            Err(io::Error::other("synthetic write failure"))
        }

        fn flush(&mut self) -> io::Result<()> {
            Ok(())
        }
    }

    #[test]
    fn failed_scaffold_write_removes_incomplete_file() {
        let temp = tempdir().unwrap();
        let target = temp.path().join("incomplete.txt");
        fs::write(&target, "").unwrap();

        let error =
            write_created_content(FailingWriter, &target, "incomplete.txt", "content").unwrap_err();

        assert!(error.to_string().contains("failed to write scaffold file"));
        assert!(!target.exists());
    }

    #[test]
    fn generated_templates_follow_package_version_and_config_defaults() {
        let workflow = ci_template();
        assert!(workflow.contains(&format!("doxguard@{} ", env!("CARGO_PKG_VERSION"))));
        assert!(!workflow.contains("__DOXGUARD_VERSION__"));

        let config: crate::config::Config = serde_json::from_str(CONFIG_TEMPLATE).unwrap();
        config.validate().unwrap();
        assert_eq!(
            config.max_file_size,
            crate::config::Config::default().max_file_size
        );
        assert_eq!(
            config.fail_on_skip,
            crate::config::Config::default().fail_on_skip
        );
    }
}
